name: Terraform Plan

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-plan.yml"

  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::585706662322:role/github-terraform-role
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color | tee plan.txt
      - name: Upload Terraform Plan
          uses: actions/upload-artifact@v4
          with:
            name: terraform-plan
            path: terraform/plan.txt